### PR TITLE
Add implementation for Chez Scheme.

### PR DESCRIPTION
**Pull request by mnieper**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Marc, do you have a comment on this pull request?  I see "mnieper commented 4 hours ago," but there's no text to the message.

**Comment by mnieper** [comment]
I left the message box empty.  The only relevant comment is the title: "Add
implementation for Chez Scheme." :-)

Am Mo., 7. Nov. 2022 um 20:59 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

**Comment by arthurgleckler** [comment]
Sorry, I was confused.  I was working with two people on two different pull requests at the same time, and I somehow thought that you were commenting on a pull request that he had provided.

Merged and pushed.

Thanks.

**Comment by mnieper** [comment]
Thank you!

Am Mo., 7. Nov. 2022 um 21:54 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

**Pull request merged**
